# Generated by Django 3.0 on 2019-12-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
